- name: Setup local environment
  hosts: moja
  user: admjakub_brand
  gather_facts: false
  roles:
    - bash
    - bosh
    - k8s
#  tasks:
#  - name: first debug task
#    debug:
#     msg: "no task"
  vars:
    adm_login: admjakub_brand
    config_dest_dir: ~/customdot
    pureline: true
